// React/src/App.js
import { useState } from 'react';

import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import './App.css';

import Button from 'devextreme-react/button';


function App() {
  var [count, setCount] = useState(0);
  const clickHandler = () => {
    setCount(count + 1);
  }
  return (
    <div className="App">
      <Button text={`Click count: ${count}`} onClick={clickHandler} />
    </div>
  );
}

export default App;

// Vue/src/App.vue
<template>
  <Home/>
</template>

<script>

import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css'
import Home from './components/Home.vue'

export default {
  name: 'App',
  components: {
    Home
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
  margin: 50px 50px;
  width: 90vh;
}
</style>
